language: php

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

before_script:
  - ln -s .env_testing .env
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction --dev


script: phpunit
